name: fis
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - quaternionic=1.0.15
  - pandas=2.2.2
  - pip:
      - jupyter==1.1.1
      - keras==3.10.0
      - matplotlib==3.10.3
      - numpy==2.1.3
      - scikit-learn==1.7.0
      - tensorflow==2.19.0
